export const USER_SIGNIN_REQEST = "USER_SIGNIN_REQEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_SIGNOUT = "USER_SIGNIN_SIGNOUT";
